
Main:
    mongo:
        host: localhost
        port: 27017
        db: data_processor
        collection: data
    backup:
        archive: true
        archive_dir: "/Users/balakrishnamaduru/Documents/git/llama_processor/resources/output/"
    input_dir: "/Users/balakrishnamaduru/Documents/git/llama_processor/resources/data/pdf_data/"
